# Generated by Django 4.0.1 on 2022-01-18 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sulist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serious_no_urgent', models.TextField(null=True, verbose_name='중요and안급함')),
                ('serious_yes_urgent', models.TextField(null=True, verbose_name='중요and급함')),
                ('no_serious_no_urgent', models.TextField(null=True, verbose_name='안중요and안급함')),
                ('no_serious_yes_urgent', models.TextField(null=True, verbose_name='안중요and급함')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
